apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: $STAGING_CERTIFICATE_NAME
  namespace: default
spec:
  secretName: $STAGING_CERTIFICATE_NAME
  issuerRef:
    name: letsencrypt-staging
  commonName: $HOST_NAME
  dnsNames:
  - $HOST_NAME
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - $HOST_NAME
